# Generated by Django 5.0.7 on 2024-08-05 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quantumBlog', '0004_createpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createpost',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CreatePost',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
