# Generated by Django 5.0.7 on 2024-08-06 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quantumBlog', '0007_post_votes_delete_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='votes',
        ),
    ]
